# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r-version }})
    strategy:
      matrix:
        config:
          - {os: macOS-latest,   r-version: '4.1.1'}
          - {os: macOS-latest,   r-version: '3.6.3'}
          - {os: windows-latest, r-version: '4.1.1'}
          - {os: windows-latest, r-version: '3.6.3'}
          - {os: ubuntu-latest,   r-version: '4.1.1'}
          - {os: ubuntu-latest,   r-version: '3.6.3'}
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
