# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.R }})
    strategy:
      matrix:
        config:
          - {os: macOS-latest,   R: '4.1.2'}
          - {os: windows-latest, R: '4.1.2'}
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.config.R }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.R }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_github("r-lib/pillar") # issues with 1.6.5
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
